//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 08:26:25 PM CST 
//


package randy.bpel.types;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the randy.bpel.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: randy.bpel.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Receive }
     * 
     */
    public Receive createReceive() {
        return new Receive();
    }

    /**
     * Create an instance of {@link randy.bpel.types.Switch }
     * 
     */
    public randy.bpel.types.Switch createSwitch() {
        return new randy.bpel.types.Switch();
    }

    /**
     * Create an instance of {@link Process.Sequence }
     * 
     */
    public Process.Sequence createProcessSequence() {
        return new Process.Sequence();
    }

    /**
     * Create an instance of {@link Invoke }
     * 
     */
    public Invoke createInvoke() {
        return new Invoke();
    }

    /**
     * Create an instance of {@link Flow }
     * 
     */
    public Flow createFlow() {
        return new Flow();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link Process.Sequence.Switch }
     * 
     */
    public Process.Sequence.Switch createProcessSequenceSwitch() {
        return new Process.Sequence.Switch();
    }

    /**
     * Create an instance of {@link randy.bpel.types.Sequence }
     * 
     */
    public randy.bpel.types.Sequence createSequence() {
        return new randy.bpel.types.Sequence();
    }

    /**
     * Create an instance of {@link Process.Sequence.Switch.Case }
     * 
     */
    public Process.Sequence.Switch.Case createProcessSequenceSwitchCase() {
        return new Process.Sequence.Switch.Case();
    }

    /**
     * Create an instance of {@link randy.bpel.types.Case }
     * 
     */
    public randy.bpel.types.Case createCase() {
        return new randy.bpel.types.Case();
    }

}
