//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 08:26:25 PM CST 
//


package randy.bpel.types;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://schemas.xmlsoap.org/ws/2003/03/business-process/}switch"/>
 *         &lt;element ref="{http://schemas.xmlsoap.org/ws/2003/03/business-process/}invoke"/>
 *         &lt;element ref="{http://schemas.xmlsoap.org/ws/2003/03/business-process/}sequence"/>
 *         &lt;element ref="{http://schemas.xmlsoap.org/ws/2003/03/business-process/}flow"/>
 *       &lt;/choice>
 *       &lt;attribute name="name">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"switchOrInvokeOrSequence"
})
@XmlRootElement(name = "sequence")
public class Sequence {

	@XmlElements({
		@XmlElement(name = "sequence", type = Sequence.class),
		@XmlElement(name = "flow", type = Flow.class),
		@XmlElement(name = "switch", type = Switch.class),
		@XmlElement(name = "invoke", type = Invoke.class)
	})
	protected List<Object> switchOrInvokeOrSequence;
	@XmlAttribute
	protected String name;

	/**
	 * Gets the value of the switchOrInvokeOrSequence property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the switchOrInvokeOrSequence property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getSwitchOrInvokeOrSequence().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Sequence }
	 * {@link Flow }
	 * {@link Switch }
	 * {@link Invoke }
	 * 
	 * 
	 */
	public List<Object> getSwitchOrInvokeOrSequence() {
		if (this.switchOrInvokeOrSequence == null) {
			this.switchOrInvokeOrSequence = new ArrayList<Object>();
		}
		return this.switchOrInvokeOrSequence;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setName(String value) {
		this.name = value;
	}

	public void setReceive(Receive receive) {
		// TODO Auto-generated method stub

	}

}
